# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-operator
  labels:
    operator: prometheus
spec:
  replicas: {{ .Values.replicas.operator }}
  template:
    metadata:
      labels:
        operator: prometheus
    spec:
      serviceAccountName: {{ .Values.access.service_account_name }}
      containers:
       - name: prometheus-operator
         image: {{ .Values.images.operator }}
         args:
         - "--kubelet-object=kube-system/kubelet"
         - "--config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1"
         {{ if .Values.resources.enabled }}
         resources:
           requests:
             cpu: {{ .Values.resources.operator.requests.cpu }}
             memory: {{ .Values.resources.operator.requests.memory }}
           limits:
             cpu: {{ .Values.resources.operator.limits.cpu }}
             memory: {{ .Values.resources.operator.limits.memory }}
         {{ end }}
